### ISSUE TITLE
QtGui.QFileDialog.getOpenFileName() does not return correct path with PyQt4 (4.8.6) in _openFileClicked() in owl.py

### ISSUE THREAD

**Issue by sellberg** [FilipeMaia/owl#21]
Recently (last week) I got an error when opening files using the GUI interface in `owl` (passing as argument was still fine). After some debugging I found that it was related to PyQt4 (which had been installed by `brew` without my notice and has precedence over PySide in Qt.py):

=== PYSIDE ===
[test:555 18:22:51] python owl.py
I am using: 0 (0 = PySide, 1 = PyQt4, 2 = PyQt5)
Filename: /net/davinci/scratch/fhgfs/xray/amoc6914/cheetah/cheman_test/data/test/r0092_20150210_114827/amoc6914-r0092.cxi

=== PYQT4 ===
[test:556 18:23:12] python owl.py
I am using: 1 (0 = PySide, 1 = PyQt4, 2 = PyQt5)
Filename: /
Traceback (most recent call last):
  File "/Users/sellberg/uu/source/owl/owl.py", line 461, in _openFileClicked
    self._openCXIFile(fileName[0])
  File "/Users/sellberg/uu/source/owl/owl.py", line 108, in _openCXIFile
    self.fileLoader.loadFile(filename)
  File "/Users/sellberg/Documents/RESEARCH/source/owl/cxi/fileloader.py", line 45, in loadFile
    err =  self.openFile(fullFilename)
  File "/Users/sellberg/Documents/RESEARCH/source/owl/cxi/fileloader.py", line 26, in openFile
    self.f = h5py.File(fullFilename,mode)#,libver='latest')
  File "/Library/Python/2.7/site-packages/h5py/_hl/files.py", line 222, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/Library/Python/2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:1812)
IOError: Unable to open file (File read failed: time = tue feb 10 18:23:34 2015
, filename = '/', file descriptor = 19, errno = 21, error message = 'is a directory', buf = 0x7fff58dd3220, total read size = 8, bytes this sub-read = 8, bytes actually read = 18446744073709551615, offset = 0)

The reason for this is that PySide (1.2.2) returns tuple-nested unicode and PyQt4 (4.8.6) returns unicode when calling QtGui.QFileDialog.getOpenFileName(). Will submit a quick and dirty fix for this now, but there may be a better solution to this issue...

**Comment by sellberg** [comment]
https://github.com/FilipeMaia/owl/commit/8bae23519d54cccf32e3537343b117df2e1cb58b solved this, you may wanna merge this to other branches
